import {
  BellOff,
  CalendarClock,
  CircleCheck,
  CircleDot,
  ClipboardCheck,
  Clock,
  CornerDownRight,
  Database,
  GitBranch,
  Inbox,
  PhoneCall,
  RotateCcw,
  type LucideIcon,
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorAlert } from "@/components/common/ErrorAlert";
import { ToneBadge } from "@/components/StatusBadge";
import type { JourneyEdge, JourneyNode } from "@/lib/types";

// The journey graph is generated by the wizard (backend:
// services/journey.py's generate_journey) and is not editable from the
// dashboard — this tab renders it read-only, in graph order, so you can see
// which nodes exist and how the outcome branches are wired.

// Icons keyed by the exact NodeInstance.name strings in JOURNEY_STEPS; any
// other name gets a generic dot, so a renamed step only loses its icon.
const NODE_ICONS: Record<string, LucideIcon> = {
  "Lead Received": Inbox,
  "Business Hours": Clock,
  "DND Check": BellOff,
  Communication: PhoneCall,
  Completed: CircleCheck,
  QA: ClipboardCheck,
  "CRM Update": Database,
  Retry: RotateCcw,
  Callback: CalendarClock,
};

// Walk the graph from the node with no incoming edges, following outgoing
// edges breadth-first, so the list reads in execution order rather than in
// whatever order the API returned rows. Nodes unreachable from the entry
// point are appended at the end rather than dropped.
function orderNodes(nodes: JourneyNode[], edges: JourneyEdge[]): JourneyNode[] {
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const hasIncoming = new Set(edges.map((e) => e.target_node));
  const queue = nodes.filter((n) => !hasIncoming.has(n.id)).map((n) => n.id);

  const seen = new Set<number>();
  const ordered: JourneyNode[] = [];
  while (queue.length > 0) {
    const id = queue.shift() as number;
    if (seen.has(id)) continue;
    seen.add(id);
    const node = byId.get(id);
    if (node) ordered.push(node);
    for (const edge of edges) {
      if (edge.source_node === id && !seen.has(edge.target_node)) {
        queue.push(edge.target_node);
      }
    }
  }
  for (const node of nodes) {
    if (!seen.has(node.id)) ordered.push(node);
  }
  return ordered;
}

function NodeStep({
  node,
  index,
  isLast,
  outgoing,
  nodeNames,
}: {
  node: JourneyNode;
  index: number;
  isLast: boolean;
  outgoing: JourneyEdge[];
  nodeNames: Map<number, string>;
}) {
  const Icon = NODE_ICONS[node.name] ?? CircleDot;
  return (
    <li className="relative flex gap-4 pb-6 last:pb-0">
      {/* Connector line down to the next step */}
      {!isLast && <span className="absolute left-5 top-11 bottom-0 w-px bg-border" aria-hidden="true" />}
      <div
        className={`relative z-10 w-10 h-10 shrink-0 rounded-full flex items-center justify-center ${
          node.enabled ? "bg-accent text-primary" : "bg-muted text-muted-foreground"
        }`}
      >
        <Icon className="w-5 h-5" />
      </div>
      <div className="flex-1 min-w-0 rounded-lg border border-border bg-card p-4">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs text-muted-foreground tabular-nums">{index + 1}.</span>
          <p className="text-sm font-semibold text-foreground">{node.name}</p>
          <ToneBadge tone="muted" className="normal-case font-mono text-[10px]">
            {node.node_template_type}
          </ToneBadge>
          {!node.enabled && (
            <ToneBadge tone="warn" className="normal-case">
              disabled
            </ToneBadge>
          )}
        </div>

        {Object.keys(node.config).length > 0 && (
          <dl className="mt-3 grid grid-cols-[minmax(0,10rem)_1fr] gap-x-3 gap-y-1 text-xs">
            {Object.entries(node.config).map(([key, value]) => (
              <div key={key} className="contents">
                <dt className="text-muted-foreground truncate">{key}</dt>
                <dd className="min-w-0 break-all font-mono text-foreground/80">
                  {typeof value === "object" && value !== null ? JSON.stringify(value) : String(value)}
                </dd>
              </div>
            ))}
          </dl>
        )}

        {outgoing.length > 0 && (
          <ul className="mt-3 pt-3 border-t border-border flex flex-wrap gap-2">
            {outgoing.map((edge) => (
              <li
                key={edge.id}
                className="inline-flex items-center gap-1.5 rounded-md bg-muted px-2 py-1 text-xs text-muted-foreground"
              >
                <CornerDownRight className="w-3 h-3" />
                {/* An empty condition means the edge always fires — QA and CRM
                    Update are unconditional side effects, not routing. */}
                <span>{edge.condition === "" ? "always" : edge.condition}</span>
                <span>→</span>
                <span className="font-medium text-foreground">
                  {nodeNames.get(edge.target_node) ?? `#${edge.target_node}`}
                </span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </li>
  );
}

export function JourneyTab({
  journeyData,
  journeyLoading,
  journeyError,
}: {
  journeyData: { nodes: JourneyNode[]; edges: JourneyEdge[] } | null;
  journeyLoading: boolean;
  journeyError: string | null;
}) {
  if (journeyLoading && !journeyData) {
    return (
      <div className="space-y-3">
        {[0, 1, 2].map((i) => (
          <Skeleton key={i} className="h-24 rounded-xl" />
        ))}
      </div>
    );
  }

  if (journeyError) {
    return <ErrorAlert message={journeyError} />;
  }

  const nodes = journeyData?.nodes ?? [];
  const edges = journeyData?.edges ?? [];

  if (nodes.length === 0) {
    return (
      <EmptyState
        icon={GitBranch}
        title="No journey nodes yet"
        description="This process agent has no journey nodes yet."
      />
    );
  }

  const nodeNames = new Map(nodes.map((n) => [n.id, n.name]));
  const ordered = orderNodes(nodes, edges);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Journey</CardTitle>
        <CardDescription>Generated from the wizard — read-only.</CardDescription>
      </CardHeader>
      <CardContent>
        <ol>
          {ordered.map((node, i) => (
            <NodeStep
              key={node.id}
              node={node}
              index={i}
              isLast={i === ordered.length - 1}
              outgoing={edges.filter((e) => e.source_node === node.id)}
              nodeNames={nodeNames}
            />
          ))}
        </ol>
      </CardContent>
    </Card>
  );
}
