import { Card, CardHeader } from "@/components/Card";
import type { JourneyEdge, JourneyNode } from "@/lib/types";

// The journey graph is generated by the wizard (backend:
// services/journey.py's generate_journey) and is not editable from the
// dashboard — this tab renders it read-only, in graph order, so you can see
// which nodes exist and how the outcome branches are wired.

// Walk the graph from the node with no incoming edges, following outgoing
// edges breadth-first, so the list reads in execution order rather than in
// whatever order the API returned rows. Nodes unreachable from the entry
// point are appended at the end rather than dropped.
function orderNodes(nodes: JourneyNode[], edges: JourneyEdge[]): JourneyNode[] {
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const hasIncoming = new Set(edges.map((e) => e.target_node));
  const queue = nodes.filter((n) => !hasIncoming.has(n.id)).map((n) => n.id);

  const seen = new Set<number>();
  const ordered: JourneyNode[] = [];
  while (queue.length > 0) {
    const id = queue.shift() as number;
    if (seen.has(id)) continue;
    seen.add(id);
    const node = byId.get(id);
    if (node) ordered.push(node);
    for (const edge of edges) {
      if (edge.source_node === id && !seen.has(edge.target_node)) {
        queue.push(edge.target_node);
      }
    }
  }
  for (const node of nodes) {
    if (!seen.has(node.id)) ordered.push(node);
  }
  return ordered;
}

function NodeCard({
  node,
  outgoing,
  nodeNames,
}: {
  node: JourneyNode;
  outgoing: JourneyEdge[];
  nodeNames: Map<number, string>;
}) {
  return (
    <Card className="p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-sm font-semibold text-gray-800">{node.name}</p>
          <p className="text-xs text-gray-400 mt-0.5">{node.node_template_type}</p>
        </div>
        {!node.enabled && (
          <span className="rounded-full border border-gray-200 px-2 py-0.5 text-[10px] text-gray-400">
            disabled
          </span>
        )}
      </div>

      {Object.keys(node.config).length > 0 && (
        <dl className="mt-3 space-y-1">
          {Object.entries(node.config).map(([key, value]) => (
            <div key={key} className="flex gap-2 text-xs">
              <dt className="shrink-0 text-gray-400">{key}</dt>
              <dd className="min-w-0 break-all text-gray-600">
                {typeof value === "object" && value !== null
                  ? JSON.stringify(value)
                  : String(value)}
              </dd>
            </div>
          ))}
        </dl>
      )}

      {outgoing.length > 0 && (
        <ul className="mt-3 space-y-1 border-t border-gray-100 pt-2">
          {outgoing.map((edge) => (
            <li key={edge.id} className="text-xs text-gray-500">
              <span className="text-gray-400">
                {/* An empty condition means the edge always fires — QA and CRM
                    Update are unconditional side effects, not routing. */}
                {edge.condition === "" ? "always" : edge.condition}
              </span>
              {" → "}
              <span className="text-gray-700">
                {nodeNames.get(edge.target_node) ?? `#${edge.target_node}`}
              </span>
            </li>
          ))}
        </ul>
      )}
    </Card>
  );
}

export function JourneyTab({
  journeyData,
  journeyLoading,
  journeyError,
}: {
  journeyData: { nodes: JourneyNode[]; edges: JourneyEdge[] } | null;
  journeyLoading: boolean;
  journeyError: string | null;
}) {
  if (journeyLoading && !journeyData) {
    return (
      <div className="space-y-3">
        {[0, 1, 2].map((i) => (
          <div key={i} className="h-24 animate-pulse rounded-xl bg-gray-100" />
        ))}
      </div>
    );
  }

  if (journeyError) {
    return (
      <Card className="p-5">
        <p className="text-sm text-red-600">{journeyError}</p>
      </Card>
    );
  }

  const nodes = journeyData?.nodes ?? [];
  const edges = journeyData?.edges ?? [];

  if (nodes.length === 0) {
    return (
      <Card className="p-5">
        <p className="text-sm text-gray-500">
          This process agent has no journey nodes yet.
        </p>
      </Card>
    );
  }

  const nodeNames = new Map(nodes.map((n) => [n.id, n.name]));
  const ordered = orderNodes(nodes, edges);

  return (
    <Card className="pb-5">
      <CardHeader
        title="Journey"
        hint="Generated from the wizard — read-only."
      />
      <div className="space-y-3 px-5">
        {ordered.map((node) => (
          <NodeCard
            key={node.id}
            node={node}
            outgoing={edges.filter((e) => e.source_node === node.id)}
            nodeNames={nodeNames}
          />
        ))}
      </div>
    </Card>
  );
}
