# Generated by Django 6.0.7 on 2026-07-10 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=128)),
                ('status', models.CharField(default='running', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('current_node', models.CharField(blank=True, default='', max_length=128)),
                ('variables', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('default_config', models.JSONField(default=dict)),
                ('schema', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64)),
                ('event_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='telehub.execution')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telehub.execution')),
                ('node_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='telehub.nodeinstance')),
            ],
        ),
        migrations.AddField(
            model_name='nodeinstance',
            name='node_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='telehub.nodetemplate'),
        ),
        migrations.CreateModel(
            name='ProcessAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='draft', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_agents', to='telehub.department')),
            ],
        ),
        migrations.AddField(
            model_name='nodeinstance',
            name='process_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='telehub.processagent'),
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, default='', max_length=64)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='telehub.nodeinstance')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='telehub.nodeinstance')),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='telehub.processagent')),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('field_mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to='telehub.processagent')),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='process_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='telehub.processagent'),
        ),
        migrations.CreateModel(
            name='QAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, default='', max_length=32)),
                ('hallucination_score', models.FloatField(blank=True, null=True)),
                ('lead_score', models.FloatField(blank=True, null=True)),
                ('compliance_score', models.FloatField(blank=True, null=True)),
                ('bot_failure', models.BooleanField(default=False)),
                ('hot_lead', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('raw_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_result', to='telehub.execution')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('secret', models.CharField(blank=True, default='', max_length=128)),
                ('schema', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='telehub.processagent')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_integrations', to='telehub.integration')),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_integrations', to='telehub.processagent')),
            ],
            options={
                'unique_together': {('process_agent', 'integration')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('type', models.CharField(default='string', max_length=32)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='telehub.processagent')),
            ],
            options={
                'unique_together': {('process_agent', 'key')},
            },
        ),
    ]
