# Generated by Django 6.0.7 on 2026-07-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='campaign_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
