# Generated by Django 6.0.7 on 2026-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehub', '0002_execution_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='next_execution',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
