# Generated by Django 6.0.7 on 2026-09-03 09:36

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehub', '0003_execution_attempt_count_execution_next_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmnichannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, default='', max_length=32)),
                ('variables', models.JSONField(default=list)),
                ('whatsapp_template', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_curl', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processagent',
            name='analytics_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='variable',
            name='label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='variable',
            name='source',
            field=models.CharField(choices=[('business_rules', 'Business Rules'), ('analytics', 'Analytics')], default='business_rules', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('process_agent', 'key', 'source')},
        ),
        migrations.AddIndex(
            model_name='execution',
            index=django.contrib.postgres.indexes.GinIndex(fields=['variables'], name='execution_variables_gin'),
        ),
        migrations.AddField(
            model_name='omnichannelconfig',
            name='process_agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='omnichannel', to='telehub.processagent'),
        ),
    ]
