# Generated by Django 6.0.7 on 2026-09-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehub', '0005_qaresult_missing_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_journeys', to='telehub.processagent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='current_bot_journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='telehub.botjourney'),
        ),
        migrations.AddField(
            model_name='nodeinstance',
            name='bot_journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='telehub.botjourney'),
        ),
        migrations.CreateModel(
            name='VoiceBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('communication_type', models.CharField(blank=True, default='', max_length=32)),
                ('bot_name', models.CharField(blank=True, default='', max_length=128)),
                ('bot_id', models.CharField(blank=True, default='', max_length=128)),
                ('dids', models.JSONField(default=list)),
                ('api_url', models.CharField(blank=True, default='', max_length=255)),
                ('script', models.TextField(blank=True, default='')),
                ('webhook_schema', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_bots', to='telehub.processagent')),
            ],
        ),
        migrations.AddField(
            model_name='botjourney',
            name='voice_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journeys', to='telehub.voicebot'),
        ),
    ]
