# Generated by Django 5.2.17 on 2026-09-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telehub', '0007_backfill_default_bot_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicebot',
            name='process_agent',
        ),
    ]
