# Generated by Django 5.2.17 on 2026-10-07 08:03

import django.db.models.deletion
from django.db import migrations, models


def copy_curl_to_t1(apps, schema_editor):
    """The pre-POC single curl becomes template T1 (never overwrites an existing T1)."""
    OmnichannelConfig = apps.get_model("telehub", "OmnichannelConfig")
    for config in OmnichannelConfig.objects.exclude(whatsapp_curl=""):
        curls = dict(config.whatsapp_curls or {})
        if not curls.get("T1"):
            curls["T1"] = config.whatsapp_curl
            config.whatsapp_curls = curls
            config.save(update_fields=["whatsapp_curls"])


class Migration(migrations.Migration):

    dependencies = [
        ('telehub', '0008_remove_voicebot_process_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnichannelconfig',
            name='auto_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnichannelconfig',
            name='whatsapp_curls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='WhatsAppSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=16)),
                ('trigger', models.CharField(default='auto', max_length=16)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sends', to='telehub.execution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('trigger', 'auto')), fields=('execution',), name='unique_auto_whatsapp_send_per_execution')],
            },
        ),
        migrations.RunPython(copy_curl_to_t1, migrations.RunPython.noop),
    ]
